### ISSUE TITLE
Instructions - build, install, run

### ISSUE THREAD

**Issue by blakemcbride** [barry-scott/BarrysEmacs#4]
Hi Barry,

Sorry about beating this issue to death, but it really is a problem.  While I can "figure it out", besides being at least as busy as you, most people want to download, build, and run.  From that point they can evaluate their interest further.  If they can't even build it, most will give up at that point.

After some blips, I found the following build instructions that worked for me on Linux:

```
(go to a directory where you wish the build to take place)
git clone https://github.com/barry-scott/BarrysEmacs.git
cd BarrysEmacs/Imports
svn co https://svn.code.sf.net/p/cxx/code/trunk/CXX pycxx-7.0.0
cd ../Builder
source builder_custom_init.sh
./build-linux.sh
```

Now, after successfully building, I have no idea how to install it.  Once installed, I have no idea how to start it up.  When it starts up, I have no idea where its user config files are and what the process is - where the user custom files are.....

For someone who knows the answers, it would probably take an hour or two to create these docs, and everyone will know how to get it up and running.

If you like, I am willing to update INSTALL.html to include the aforementioned build instructions as well as the suggested additional documentation if you can provide me the information in rough draft.  I can work back and forth with you to make it clean and easy.

Thanks.

Blake McBride

**Comment by blakemcbride** [comment]
I discovered that I can install (from the Builder directory) with:

`sudo cp -rp ../Kits/Linux/DPKG/tree/usr/local/bemacs8/* /usr/local`

However, when I run `bemacs` I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/bemacs_server", line 4, in <module>
    import be_main
ImportError: No module named 'be_main'
```

**Comment by blakemcbride** [comment]
After my install, the following seems to run it:

```
export BEMACS_EMACS_LIBRARY=/usr/local/lib/bemacs
python3 -u /usr/local/lib/bemacs/be_main.py
```

That should probably be in a shell script in the /usr/local/bin directory.

**Comment by barry-scott** [comment]
The steps you are using are in the INSTALL.html that I updated today and I hope pushed before you did the latest build.

I'm happy to receive improvements to the docs.

I think the Builder/local-install-linux.sh should install without needing to package bemacs onto a .deb.

Then you should have /usr/local/bemacs8/bin/bemacs to run.

ImportError: No module named 'be_main' happend because its installed in the wrong folder.

If you want to use /usr/local/bin and not /usr/local/bemacs8/bin then you need to build with the
difference DESTDIR. The files that are installed have to have paths hard wired and the default
is to use /usr/local/bemacs8 as the DESTDIR.

I'll add documenting the DESTDIR to my todo list for linux.mak.

Barry

**Comment by lurch** [comment]
On a similar note, I wonder if there should be a MarkDown version of the Install instructions?

Here's the user-process I just did:
1. Watched https://www.youtube.com/watch?v=P5fJdIPUPY4
2. Thought "Hmmm, that looks interesting"
3. Googled for "Barrys Emacs"
4. Clicked through to the website http://www.barrys-emacs.org/
5. Got surprised by the spartan presentation ;)  Not even any screenshots?
6. Read "Linux : Source builds tested on Fedora."
7. Clicked through to the GitHub link https://github.com/barry-scott/BarrysEmacs
8. Read the very brief README.md, wondering where the install instructions were
9. Spotted the INSTALL.html file in the list-of-files, so clicked on that
10. Saw that GH displays the raw HTML, which obviously isn't very human-readable
11. Clicked on the "Raw" button in the hope that the raw HTML would then get rendered
12. Saw that it _still_ displays the raw HTML
13. Decide I can't be bothered any more...
14. Submit this bug-comment :-)

Also, a link from https://github.com/barry-scott/BarrysEmacs to http://www.barrys-emacs.org/ would probably be useful?

(instead of converting the install instructions from html to MD, perhaps another option might be copying INSTALL.html to http://www.barrys-emacs.org/ and providing a prominent link to it?)

**Comment by barry-scott** [comment]
Thanks for the details Andrew.

I will follow up shortly.

Barry

**Comment by barry-scott** [comment]
@lurch  README.rst has been updated with links as you suggested. needed to find the way to show HTML from a github repo.

This is what I ended up using:

http://htmlpreview.github.io/?https://github.com/barry-scott/BarrysEmacs/blob/master/INSTALL.htm

I still have more to do before I close this bug.

**Comment by lurch** [comment]
Thanks Barry, that looks much better :-)
(I'll see if I find time one evening next week to give it a try)

**Comment by barry-scott** [comment]
@lurch screen shot added to web site

**Comment by barry-scott** [comment]
I have updated the README.html with improved instruction and since this issue was raise a number of build improvements. Re-open if you think I need to do more.
